### ISSUE TITLE
Tournament mode: change so admin spectators can share chat

### ISSUE THREAD

**Issue by mysticamber** [Factorio-Biter-Battles/Factorio-Biter-Battles#39]
In tournament mode, spectator chat is not shared with the teams. 
It makes it hard for admins to communicate and respond to questions/concerns 

Code is in functions.lua -> Public.share_chat method

**Comment by 1pulse** [comment]
Very important to keep spectator chat locked, and useful I agree about admin have to do it :+1:

**Comment by kajendra** [comment]
Note to self (and any others) found the line where this needs to be modified:
https://github.com/1pulse/Factorio-Biter-Battles/blob/3616e030984b53fe27a3489a1a79610d44d86f57/maps/biter_battles_v2/functions.lua#L243

**Comment by guymaor86** [comment]
This is resolved I think

**Comment by mysticamber** [comment]
> This is resolved I think

Not yet resolved. They just disable tournament mode after the players have been picked, but if you kept it in tournament mode, they won't see spectator chat.
